apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: freedom-tech-guestbook
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.webhook: ""
spec:
  project: default
  source:
    repoURL: https://github.com/djenkins-freedom-tech/guestbook.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://kubernetes.default.svc
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
