apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
  annotations:
#    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argocd
     notifications.argoproj.io/subscriptions: |
        - trigger: [on-sync-succeeded]
          destinations:
            - service: slack
              recipients: [argocd]
            - service: email.gmail
              recipients: [djenkins.trss@gmail.com]
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: guestbook-ui
  template:
    metadata:
      labels:
        app: guestbook-ui
    spec:
      containers:
      - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
        name: guestbook-ui
        ports:
        - containerPort: 80
# adding some white space
#
#
# end of white space
